### ISSUE TITLE
Pressing down more than 4 keys at the same time is unreliable

### ISSUE THREAD

**Issue by SeunghunSunmoonLee** [kevinsqi/react-piano#35]
Hi, I found you can't press 6 keys at the same time in this piano. I found other piano examples be able to do so. Is this related to activeSounds setState  ? Other implementations were pure js.

**Comment by iqnivek** [comment]
Yeah, this is an open issue. I investigated this way back and I recall, at least on mac, an issue with the "ctrl" key being registered as pressed when a lot of keys are pressed down at once, which causes notes to not register due to [this line of code](https://github.com/iqnivek/react-piano/blob/master/src/ControlledPiano.js#L105), and potentially also just keydown events not firing as expected. 

I'll have to dig into it again. Any help on investigating this is welcome!

**Comment by iqnivek** [comment]
I noticed this also happens when attempting to press down any 3 keys corresponding to sequential half steps (e.g. D, D#, E).

**Comment by kevinsqi** [comment]
This appears to not be specific to this component or to React - I created a codepen that demonstrates the issue for vanilla JS: https://codepen.io/kevinqi/pen/ZPxGoa

**Comment by kevinsqi** [comment]
ahh, it appears that this could be an issue with key rollover (a property of the keyboard), not anything JS related. See https://apple.stackexchange.com/a/70430/149027. If this is the issue, then it can't be fixed - it's an inherent limitation of the keyboard you use.

Both my macbook pro keyboard and mac magic keyboard, for example, are unable to register "s" + "e" + "d" when pressed down simultaneously. However, when I tested with a Das keyboard, it was able to register all 3 simultaneously.

@SeunghunSunmoonLee you mentioned that "I found other piano examples be able to do [6 keys at the same time]". Could you link me to an example piano where that works?

**Comment by kevinsqi** [comment]
Going to close this given that I think this is a hardware keyboard rollover issue and not related to the library, but if anyone can demonstrate otherwise, don't hesitate to reopen the issue.
