### ISSUE TITLE
Separating the utilities from the UI

### ISSUE THREAD

**Issue by ritz078** [kevinsqi/react-piano#45]
I only need the utilities like MidiNumbers, keyboardShortcuts etc. Do you think it makes sense to separate them so that they can be used in the generic projects who want to use a different UI?

**Comment by kevinsqi** [comment]
I think that's reasonable! I'd be down to extract those utilities into a separate repo (perhaps "react-piano-utils") and give you write access. However, I'd prefer to keep a copy of those utilities in react-piano as well (instead of having react-piano-utils as a dependency) so I don't have to necessarily create two PRs to make a change to the utils. Sound good?

Down the line, I'd be interested in seeing if I could support alternative UIs with react-piano, allowing you to define how you'd like to render the entire UI. Would that be interesting to you or would you always want to implement your own piano component instead?

(by the way, I've played around with raaga and I think it's awesome! I'm working on something similar and sometimes look to it for inspiration)

**Comment by ritz078** [comment]
> I think that's reasonable! I'd be down to extract those utilities into a separate repo (perhaps "react-piano-utils") and give you write access. However, I'd prefer to keep a copy of those utilities in react-piano as well (instead of having react-piano-utils as a dependency) so I don't have to necessarily create two PRs to make a change to the utils. Sound good?


- name can be simple `piano-utils` as there won't be react in that.
- I don't think it will be changed frequently once stable. Also if you keep a duplicate in react-native-piano, in case you find a bug, we will have to make changes at both places. That's duplication.

> Down the line, I'd be interested in seeing if I could support alternative UIs with react-piano, allowing you to define how you'd like to render the entire UI. Would that be interesting to you or would you always want to implement your own piano component instead?


I implemented it because I wanted to have control initially as I wasn't sure what functionalities I might need there. option to make it customizable is most welcome.

> (by the way, as a total aside, I've played around with raaga and I think it's awesome! I'm working on something similar and sometimes look to it for inspiration)


Thanks a lot. I have a lot of ideas for it and any feedback or suggestion is most welcome. I will be launching it soon. Your project was the one which was a huge time saver for me and I am so grateful for that.

**Comment by kevinsqi** [comment]
> name can be simply piano-utils as there won't be react in that.

That's a better name - I'll use that 👍 

> I don't think it will be changed frequently once stable. Also if you keep a duplicate in react-native-piano, in case you find a bug, we will have to make changes at both places. That's duplication.

Yup. But the amount of code is quite small and won't change too often, so I'm pretty comfortable with that small amount of duplication. And not having to coordinate this with react-piano will make it easier to iterate on! Down the line, if there's another consumer library (e.g. react-native-piano), we could always change it to be a true dependency, too.

> Thanks a lot. I have a lot of ideas for it and any feedback or suggestion is most welcome. I will be launching it soon. Your project was a huge time saver for me and I am so grateful for that.

Thanks man! ❤️

**Comment by kevinsqi** [comment]
@ritz078 just created and published piano-utils! Invited you as a collaborator with push access.
https://github.com/kevinsqi/piano-utils
